-- 코드를 입력하세요
SELECT RH.HISTORY_ID, 
    FLOOR(IF(RHD.RENTAL_PERIOD >= 90, (CC.DAILY_FEE*((100-(SELECT DP.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP WHERE DP.CAR_TYPE = '트럭' AND DP.DURATION_TYPE like '%90%'))/100))*RHD.RENTAL_PERIOD,
      IF(RHD.RENTAL_PERIOD >= 30, (CC.DAILY_FEE*((100-(SELECT DP.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP WHERE DP.CAR_TYPE = '트럭' AND DP.DURATION_TYPE like '%30%'))/100))*RHD.RENTAL_PERIOD, 
        IF(RHD.RENTAL_PERIOD >= 7, (CC.DAILY_FEE*((100-(SELECT DP.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP WHERE DP.CAR_TYPE = '트럭' AND DP.DURATION_TYPE like '%7%'))/100))*RHD.RENTAL_PERIOD, CC.DAILY_FEE*RHD.RENTAL_PERIOD)))) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR CC ON RH.CAR_ID = CC.CAR_ID AND CC.CAR_TYPE = '트럭'
JOIN (SELECT RH2.HISTORY_ID, DATEDIFF(RH2.END_DATE, RH2.START_DATE)+1 AS RENTAL_PERIOD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH2) RHD ON RHD.HISTORY_ID = RH.HISTORY_ID
ORDER BY FEE DESC, RH.HISTORY_ID DESC;

