-- 코드를 입력하세요
(SELECT PT_NAME, PT_NO, GEND_CD, AGE, TLNO
FROM PATIENT
WHERE AGE <= 12 and GEND_CD = 'W' and TLNO is not null)
UNION
(SELECT PT_NAME, PT_NO, GEND_CD, AGE, "NONE" AS TLNO
FROM PATIENT
WHERE AGE <= 12 and GEND_CD = 'W' and TLNO is null)
ORDER BY AGE DESC, PT_NAME ASC;