-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, count(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT a.CAR_ID
                FROM (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, count(HISTORY_ID) AS RECORDS
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    GROUP BY MONTH(START_DATE), CAR_ID
                    HAVING MONTH > 7 AND MONTH < 11
                    ORDER BY MONTH ASC, CAR_ID DESC) a
                GROUP BY a.CAR_ID
                HAVING sum(a.RECORDS) > 4) AND MONTH(START_DATE) > 7 AND MONTH(START_DATE) < 11
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;