-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, if(STATUS = 'SALE', '판매중', if(STATUS = 'RESERVED', '예약중', '거래완료')) STATUS
FROM USED_GOODS_BOARD
WHERE date_format(CREATED_DATE, '%Y-%m-%d') = '2022-10-05'
ORDER BY BOARD_ID DESC;